### ISSUE TITLE
Having an issue with installing

### ISSUE THREAD

**Issue by kidis21** [cristian-swf/fitbit-sdk5-converter#1]
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/fitbit-sdk5-converter - Not found
npm ERR! 404
npm ERR! 404  'fitbit-sdk5-converter@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\F\AppData\Roaming\npm-cache\_logs\2021-02-15T17_32_26_439Z-debug.log
Install for [ 'fitbit-sdk5-converter@latest' ] failed with code 1

=====================

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'fitbit-sdk5-converter@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\F\\AppData\\Roaming\\npm-cache\\_npx\\13280',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose npm-session 24eafa808ae781a3
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 http://registry.npmjs.org/fitbit-sdk5-converter 1244ms
8 http fetch GET 404 http://registry.npmjs.org/fitbit-sdk5-converter 831ms
9 silly fetchPackageMetaData error for fitbit-sdk5-converter@latest 404 Not Found - GET http://registry.npmjs.org/fitbit-sdk5-converter - Not found
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 2106ms
12 verbose stack Error: 404 Not Found - GET http://registry.npmjs.org/fitbit-sdk5-converter - Not found
12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid fitbit-sdk5-converter@latest
15 verbose cwd C:\111Fitbit\Projects
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fitbit-sdk5-converter@latest" "--global" "--prefix" "C:\\Users\\F\\AppData\\Roaming\\npm-cache\\_npx\\13280" "--loglevel" "error" "--json"
18 verbose node v14.15.5
19 verbose npm  v6.14.11
20 error code E404
21 error 404 Not Found - GET http://registry.npmjs.org/fitbit-sdk5-converter - Not found
22 error 404
23 error 404 'fitbit-sdk5-converter@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by cristian-swf** [comment]
It's not published in npm yet. Download the code, add your own files/resources in **copyfiles** folder, if you need, then run **npm install -g** in the downloaded folder to install it globally.
